new Vue({
  el: '#items',
  created() {
    this.paginate_total = this.items.length/this.paginate;
  },
  data: {
    active: 'link-1',
     current: 1,
     filterField: '',
     entries: null,
     show: false,
     search_filter: '',
     items: [
            { 
              name: '[Member] Statement reminder-email-1-RIE',
              color: 'green-02',
              group: 'mbr',
              sent: '51,218',
              small: '(99% Success)',
              opens: '1,921 - 8.85%  ',
              clicks: '48 - 0.22%  ',
              subject: '<Name>, don’t forget to watch your personal video update',
              time: '16/10/2020 11:09',
              url: ["https://litmus.com/pub/3bf0cf7"],
            },
            { 
              name: '[Member] Statement reminder-email-2-Non-RIE-01',
              color: 'green-02',
              group: 'mbr',
              sent: '20,683',
              small: '(99% Success)',
              opens: '2,286 - 11.05% ',
              clicks: '55 - 0.27% ',
              subject: '<Name>, don’t forget to watch your personal video update',
              time: '16/10/2020 11:09',
              url: ["https://litmus.com/pub/05ac995"],
            },
            { 
              name: '[Member] Statement reminder-email-2-Non-RIE-02',
              color: 'green-02',
              group: 'mbr',
              sent: '1,392',
              small: '(98% Success)',
              opens: '211 - 15.20%',
              clicks: '12 - 0.86%',
              subject: '<Name>, don’t forget to watch your personal video update',
              time: '16/10/2020 11:09',
              url: ["https://litmus.com/pub/db9ca64"],
            },
            { 
              name: '[Member] Statement reminder-email-2-Non-RIE-03',
              color: 'green-02',
              group: 'mbr',
              sent: '875',
              small: '(95% Success)',
              opens: '147 - 16.88% ',
              clicks: '10 - 1.15%  ',
              subject: '<Name>, don’t forget to watch your personal video update',
              time: '16/10/2020 11:09',
              url: ["https://litmus.com/pub/ddd9318"],
            },
            { 
              name: '[Member] Statement reminder-email-2-Non-RIE-04',
              color: 'green-02',
              group: 'mbr',
              sent: '7,114',
              small: '(99% Success)',
              opens: '859 - 12.08%  ',
              clicks: '23 - 0.32%  ',
              subject: '<Name>, don’t forget to watch your personal video update',
              time: '16/10/2020 11:09',
              url: ["https://litmus.com/pub/927a9d7"],
            },
            { 
              name: '[Member] Statement Email-2-Non-RIE-04',
              color: 'green-02',
              group: 'mbr',
              sent: '27,426',
              small: '(99% Success)',
              opens: '9,615 - 35.06%  ',
              clicks: '86 - 0.31% ',
              subject: '<Name>, your video is ready: see how your super’s travelling.',
              time: '18/09/2020 10:02',
              url: ["https://litmus.com/pub/d754515"],
            },
            { 
              name: '[Member] Statement Email-2-Non-RIE-03',
              color: 'green-02',
              group: 'mbr',
              sent: '9,580',
              small: '(98% Success)',
              opens: '5,423 - 56.61%  ',
              clicks: '99 - 1.03%  ',
              subject: '<Name>, your video is ready: see how your super’s travelling.',
              time: '18/09/2020 10:00',
              url: ["https://litmus.com/pub/2ff6672"],
            },
            { 
              name: '[Member] Statement Email-2-Non-RIE-02 ',
              color: 'green-02',
              group: 'mbr',
              sent: '11,676',
              small: '(98% Success)',
              opens: '5,875 - 50.32% ',
              clicks: '72 - 0.62% ',
              subject: '<Name>, your video is ready: see how your super’s travelling.',
              time: '18/09/2020 09:58',
              url: ["https://litmus.com/pub/7c6156f"],
            },
            { 
              name: '[Member] Statement Email-2-Non-RIE-01 - Wave 2',
              color: 'green-02',
              group: 'mbr',
              sent: '56,020',
              small: '(99% Success)',
              opens: '20,856 - 37.23%',
              clicks: '160 - 0.29% ',
              subject: '<Name>, your video is ready: see how your super’s travelling.',
              time: '17/09/2020 10:00',
              url: ["https://litmus.com/pub/cb722aa"],
            },
            { 
              name: '[Member] Statement Email-2-Non-RIE-01 - Wave 1',
              color: 'green-02',
              group: 'mbr',
              sent: '37,774',
              small: '(99% Success)',
              opens: '14,069 - 37.25% ',
              clicks: '121 - 0.32% ',
              subject: '<Name>, your video is ready: see how your super’s travelling.',
              time: '16/09/2020 09:58',
              url: ["https://litmus.com/pub/cb722aa"],
            },
            { 
              name: '[Member] Statement video snapshots email-1-RIE wave 6',
              color: 'green-02',
              group: 'mbr',
              sent: '15,817',
              small: '(99% Success)',
              opens: '6,789 - 42.92% ',
              clicks: '66 - 0.42% ',
              subject: '<Name>, your video is ready: see how your super’s travelling.',
              time: '16/09/2020 09:56',
              url: ["https://litmus.com/pub/d38d1a1"],
            },
            { 
              name: '[Member] Statement video snapshots email-1-RIE wave 5',
              color: 'green-02',
              group: 'mbr',
              sent: '54,182',
              small: '(99% Success)',
              opens: '23,610 - 43.58%  ',
              clicks: '23,610 - 43.58%  ',
              subject: '<Name>, your video is ready: see how your super’s travelling.',
              time: '15/09/2020 09:59',
              url: ["https://litmus.com/pub/d38d1a1"],
            },
            { 
              name: '[Member] Statement video snapshots email-1-RIE wave 4',
              color: 'green-02',
              group: 'mbr',
              sent: '54,308',
              small: '(99% Success)',
              opens: '23,995 - 44.18% ',
              clicks: '195 - 0.36%  ',
              subject: '<Name>, your video is ready: see how your super’s travelling.',
              time: '14/09/2020 ',
              url: ["https://litmus.com/pub/d38d1a1"],
            },
            { 
              name: '[Member] Statement video snapshots email-1-RIE wave 3',
              color: 'green-02',
              group: 'mbr',
              sent: '54,241',
              small: '(99% Success)',
              opens: '23,323 - 43.00%',
              clicks: '218 - 0.40%',
              subject: '<Name>, your video is ready: see how your super’s travelling.',
              time: '11/09/2020 09:56',
              url: ["https://litmus.com/pub/d38d1a1"],
            },
            { 
              name: '[Member] Statement video snapshots email-1-RIE wave 2',
              color: 'green-02',
              group: 'mbr',
              sent: '54,236',
              small: '(99% Success)',
              opens: '23,269 - 42.90% ',
              clicks: '221 - 0.41%  ',
              subject: '<Name>, your video is ready: see how your super’s travelling.',
              time: '10/09/2020 10:01',
              url: ["https://litmus.com/pub/d38d1a1"],
            },
            { 
              name: '[Member] Statement video snapshots email-1-RIE subject line A',
              color: 'green-02',
              group: 'mbr',
              sent: '18,077 (A)',
              small: '(99% Success)',
              opens: '7,237 -  40.03% ',
              clicks: '57 - 0.32% ',
              subject: 'A short video we’ve made just for you, <Name>.',
              time: '09/09/2020 10:00',
              url: ["https://litmus.com/pub/d38d1a1"],
            },
            { 
              name: '[Member] Statement video snapshots email-1-RIE subject line B',
              color: 'green-02',
              group: 'mbr',
              sent: '18,103 (B)',
              small: '(99% Success)',
              opens: '7,911 - 43.70% ',
              clicks: '82 - 0.45% ',
              subject: '<Name>, your video is ready: see how your super’s travelling.',
              time: '09/09/2020 10:01',
              url: ["https://litmus.com/pub/d38d1a1"],
            },
            { 
              name: '[Member] Statement video snapshots email-1-RIE subject line C',
              color: 'green-02',
              group: 'mbr',
              sent: '18,055 (C)',
              small: '(99% Success)',
              opens: '7,636 - 42.29% ',
              clicks: '83 - 0.46%',
              subject: '<Name>, watch your video to see how your super’s tracking.',
              time: '09/09/2020 10:01',
              url: ["https://litmus.com/pub/d38d1a1"],
            },
            { 
              name: '[Member] Statements Super - Invalid address:  email-3-annual-statement-01',
              color: 'green-02',
              group: 'mbr',
              sent: '4,461',
              small: '(98% Success)',
              opens: '1,202 - 26.94% ',
              clicks: '206 - 4.62% ',
              subject: '<Name>, log in to see your annual statement',
              time: '02/10/2020 10:00',
              url: ["https://litmus.com/checklist/public/3ef2fb2"],
            },
            { 
              name: '[Member] Statements Super - Invalid address:  email-3-annual-statement-02 ',
              color: 'green-02',
              group: 'mbr',
              sent: '6,897',
              small: '(98% Success)',
              opens: '2,226 - 32.27% ',
              clicks: '590 - 8.55% ',
              subject: '<Name>, log in to see your annual statement',
              time: '02/10/2020 12:01',
              url: ["https://litmus.com/checklist/public/3ef2fb2"],
            },
            { 
              name: '[Member] Statements Super - Invalid address: email-3-annual-statement-03 ',
              color: 'green-02',
              group: 'mbr',
              sent: '1,867',
              small: '(95% Success)',
              opens: '743 - 39.80% ',
              clicks: '276 - 14.78% ',
              subject: '<Name>, log in to see your annual statement',
              time: '02/10/2020 15:01',
              url: ["https://litmus.com/checklist/public/3ef2fb2"],
            },
            { 
              name: '[Member] Statements Super - Under 30: email-3-annual-statement-01',
              color: 'green-02',
              group: 'mbr',
              sent: '79,002',
              small: '(99% Success)',
              opens: '29,932 - 37.89%  ',
              clicks: '5,217 - 6.60% ',
              subject: '<Name>, log in to see your annual statement',
              time: '29/09/2020 10:09',
              url: ["https://litmus.com/checklist/public/3ef2fb2"],
            },
            { 
              name: '[Member] Statements Super - 30 to 49: ',
              color: 'green-02',
              group: 'mbr',
              sent: '115,507',
              small: '(99% Success)',
              opens: '55,471 - 48.03% ',
              clicks: '15,236 - 13.19%  ',
              subject: '<Name>, log in to see your annual statement',
              time: '22/09/2020 10:04',
              url: ["https://litmus.com/pub/e58c06d"],
            },
            { 
              name: '[Member] Statements Super - 50+: email-3-annual-statement-03',
              color: 'green-02',
              group: 'mbr',
              sent: '51,089',
              small: '(98% Success)',
              opens: '31,981 - 62.61%  ',
              clicks: '14,867 - 29.10% ',
              subject: '<Name>, log in to see your annual statement',
              time: '21/09/2020 10:00',
              url: ["https://litmus.com/pub/4cf61ec"],
            },
            { 
              name: '[Member] Statements annual-statement-sis',
              color: 'green-02',
              group: 'mbr',
              sent: '5,100',
              small: '(98% Success)',
              opens: '3,806 - 74.63% ',
              clicks: '1,966 - 38.55%  ',
              subject: '<Name>, log in to see your annual statement',
              time: '09/09/2020 10:06',
              url: ["https://litmus.com/pub/04b525c"],
            },
            { 
              name: '[Member] Statements annual-statement-sis (no-address)',
              color: 'green-02',
              group: 'mbr',
              sent: '14',
              small: '(88% Success)',
              opens: '7 - 50.00% ',
              clicks: '4 - 28.57% ',
              subject: '<Name>, log in to see your annual statement',
              time: '09/09/2020 10:06',
              url: ["https://litmus.com/pub/41c8c82"],
            },
            { 
              name: '[Member] Statements AMB Invite',
              color: 'green-02',
              group: 'mbr',
              sent: '1,268',
              small: '(97% Success)',
              opens: '747 - 58.96% ',
              clicks: '32 - 2.53% ',
              subject: '<Name>, register for the 2020 Annual Member Briefing',
              time: '01/10/2020',
              url: ["https://litmus.com/pub/aac0e81"],
            },
            { 
              name: '[Member] Statements AMB Invite SIS',
              color: 'green-02',
              group: 'mbr',
              sent: '33',
              small: '(93% Success)',
              opens: '24 - 75.00% ',
              clicks: '1 - 3.13% ',
              subject: '<Name>, register for the 2020 Annual Member Briefing',
              time: '01/10/2020 10:00',
              url: ["https://litmus.com/pub/aac0e81"],
            },

            { 
              name: '[Brand] 2020-10 Super Brand Survey Core Data - Invite (A)',
              color: 'lagoon',
              group: 'brand',
              sent: '7,432 (A)',
              opens: '2,794 - 37.59%',
              clicks: '263 - 3.54%',
              subject: '<Name>, share your feedback for your chance to receive a gift card or voucher!',
              time: '08/10/2020 THU 02:19PM',
              url: ["https://email-gallery.netlify.app/emails/2020-10-mbr_super-brand-survey.html"],
            },
            { 
              name: '[Brand] 2020-10 Super Brand Survey Core Data - Invite (B)',
              color: 'lagoon',
              group: 'brand',
              sent: '7,450 (B)',
              opens: '2,770 - 37.18%',
              clicks: '249 - 3.34% ',
              subject: '<Name>, tell us your opinion about super funds and win',
              time: '08/10/2020 THU 02:19PM',
              url: ["https://email-gallery.netlify.app/emails/2020-10-mbr_super-brand-survey.html"],
            },
            { 
              name: '[Retirement Webinar] 2020-10 SA (50-65yrs) - #13 Invite',
              color: 'purple',
              group: 'event',
              sent: '6,082',
              opens: '2,857 - 46.97% ',
              clicks: '93 - 1.53% ',
              subject: 'As a valued Cbus member, we invite you to attend an upcoming webinar.',
              time: '06/10/2020 TUE 10:00AM',
              url: ["https://email-gallery.netlify.app/emails/2020-10-event_webinar-retirement-multi-event-13.html"],
            },
            { 
              name: '[Retirement Webinar Super in your 40s] 2020-09 SA (40-49yrs) - #12 Reminder',
              color: 'green',
              group: 'event',
              sent: '5,305',
              opens: '1,713 - 32.29% ',
              clicks: '26 - 0.49% ',
              subject: 'Managing super in your 40s’ webinar - there’s still spots left',
              time: '07/10/2020 WED 10:00AM',
              url: ["https://email-gallery.netlify.app/emails/Retirement webinar reminder 40-49.html"],
          },
          { 
              name: '[Retirement Webinar Super in your 40s] 2020-09 SA (40-49yrs) - #12 Invite',
              color: 'green',
              group: 'event',
              sent: '5,335',
              opens: '2,131 - 39.94% ',
              clicks: '56 - 1.05% ',
              subject: '<Name>, maximise your super in your 40s',
              time: '01/10/2020 THU 10:20AM',
              url: ["https://email-gallery.netlify.app/emails/Retirement Webinar 40-49.html"],
          },
          { 
            name: '[Retirement Webinar] 2020-09 QLD (53-65yrs) - #11 Reminder',
            color: 'purple',
            group: 'event',
            sent: '4,018',
            opens: '1,740 - 43.31%',
            clicks: '72 - 1.79% ',
            subject: '[Webinar] It’s almost time – Reserve your spot. 🔔',
            time: '14/09/2020 MON 03:00PM',
            url: ["https://email-gallery.netlify.app/emails/2020-09-event_webinar-retirement-multi-event-11-reminder"],
          },
          { 
            name: '[Retirement Webinar] 2020-09 QLD (53-65yrs) - #11 Invite',
            color: 'purple',
            group: 'event',
            sent: '4,077',
            opens: '2,145 - 52.61%',
            clicks: '104 - 2.55% ',
            subject: 'As a valued Cbus member, we invite you to attend an upcoming webinar.',
            time: '11/09/2020 FRI 01:30PM',
            url: ["https://email-gallery.netlify.app/emails/2020-09-event_webinar-retirement-multi-event-11"],
          },
            { 
              name: '[Pre-Retirement Webinar] 2020-09 QLD (43-53yrs) - #10 Reminder',
              color: 'purple',
              group: 'event',
              sent: '8,900',
              opens: '3,271 - 36.75% ',
              clicks: '57 - 0.64% ',
              subject: 'Spots are filling fast. Reserve yours today. 🔔',
              time: '09/09/2020 WED 09:00AM',
              url: ["https://email-gallery.netlify.app/emails/2020-09-event_webinar-retirement-single-event-10-reminder"],
            },
            { 
              name: '[Pre-Retirement Webinar] 2020-09 QLD (43-53yrs) - #10 Invite',
              color: 'purple',
              group: 'event',
              sent: '8,978',
              opens: '4,191 - 46.68% ',
              clicks: '84 - 0.94% ',
              subject: 'As a valued Cbus member, we invite you to attend an upcoming webinar.',
              time: '03/09/2020 THU 09:20AM',
              url: ["https://email-gallery.netlify.app/emails/2020-09-event_webinar-retirement-single-event-10"],
            },
            { 
              name: '[Retirement Webinar] 2020-08 NSW (53-65yrs) - #9 Reminder',
              color: 'purple',
              group: 'event',
              sent: '23,312',
              opens: '9,581 - 41.10%',
              clicks: '372- 1.60% ',
              subject: 'Spots are filling fast. Reserve yours today. 🔔',
              time: '20/08/2020 THU 02:00PM',
              url: ["https://email-gallery.netlify.app/emails/2020-08-event_webinar-pre-retirement--event-9.html"],
            },
            { 
              name: '[Retirement Webinar] 2020-08 NSW (53-65yrs) - #9 Invite',
              color: 'purple',
              group: 'event',
              sent: '24,117',
              opens: '12,916 - 53.56%  ',
              clicks: '520 - 2.16%  ',
              subject: '<Name>, registration is now open for Retirement Planning',
              time: '04/08/2020 TUE 03:50PM',
              url: ["https://email-gallery.netlify.app/emails/2020-08-event_webinar-pre-retirement--event-9.html"],
            },
            { 
              name: '[Pre-Retirement Webinar] 2020-08 NSW - #8 Invite',
              color: 'purple',
              group: 'event',
              sent: '434',
              opens: '203 - 46.77% ',
              clicks: '3 - 0.69%',
              subject: '<Name>, registration is now open for Pre-Retirement Planning',
              time: '04/08/2020 TUE 03:50PM',
              url: ["https://email-gallery.netlify.app/emails/2020-08-event_webinar-pre-retirement--event-8.html"],
            },
            { 
                name: '[Retirement Webinar] 2020-07 WA - #7 Reminder',
                color: 'purple',
                group: 'event',
                sent: '10,539',
                opens: '4,066 - 38.58%',
                clicks: '222 - 2.11% ',
                subject: 'Spots are filling fast. Reserve yours today. 🔔',
                time: '17/07/2020 TUE 11:11AM',
                url: ["https://email-gallery.netlify.app/emails/2020-07-event_webinar-retirement--event-7--reminder"],
              },
            { 
              name: '[Retirement Webinar] 2020-07 WA - #7 Invite (A)',
              color: 'purple',
              group: 'event',
              sent: '5,379 (A)',
              opens: '2,661 - 49.95% ',
              clicks: '136 - 2.55%  ',
              subject: 'Hi <Name>, secure your spot for our upcoming webinars',
              time: '07/07/2020 TUE 11:30AM',
              url: ["https://email-gallery.netlify.app/emails/2020-06-event_webinar-retirement--event-7.html"],
          },
          { 
            name: '[Retirement Webinars] 2020-07 WA - #7 Invite (B)',
            color: 'purple',
            group: 'event',
            sent: '5,336 (B)',
            opens: '2,910 - 54.54%',
            clicks: '154 - 2.89%',
            subject: '<Name>, registration is now open for Retirement Planning',
            time: '07/07/2020 TUE 11:30AM',
            url: ["https://email-gallery.netlify.app/emails/2020-06-event_webinar-retirement--event-7.html"],
        },

          { 
            name: '[RIF] 2020-10 (SA) - Reminder',
            color: 'gold',
            group: 'event',
            sent: '626',
            opens: '325 - 51.92% ',
            clicks: '17 - 2.72% ',
            subject: 'Cbus Webinars: Don’t miss out – Reserve your spot. 🔔',
            time: '29/09/2020 TUE 11:00AM',
            url: ["https://email-gallery.netlify.app/emails/2020-10 RIF SA Email Reminder.html"],
        },
        { 
          name: '[RIF] 2020-09 (SA) - Invite',
          color: 'gold',
          group: 'event',
          sent: '628',
          opens: '368 - 58.60% ',
          clicks: '24 - 3.82% ',
          subject: 'You’re invited to attend an exclusive member webinar',
          time: '24/09/2020 THU 11:00AM',
          url: ["https://email-gallery.netlify.app/emails/2020-09%20rif%20sept%20email%20initial%20invite"],
      },
      { 
        name: '[RIF] 2020-08 (QLD, NT & ACT) - Reminder',
        color: 'gold',
        group: 'event',
        sent: '274',
        opens: '161 - 58.76% ',
        clicks: '5 - 1.82% ',
        subject: 'Cbus Webinars: Don’t miss out – Reserve your spot. 🔔',
        time: '27/08/2020 THU 10:22AM',
        url: ["https://email-gallery.netlify.app/emails/2020-08-event__invite-retirement-sep-8-reminder.html"],
    },
    { 
      name: '[RIF] 2020-08 (NT, ACT) - Invite',
      color: 'gold',
      group: 'event',
      sent: '180',
      opens: '119 - 66.11% ',
      clicks: '7 - 3.89% ',
      subject: 'You’re invited to attend an exclusive member webinar',
      time: '12/08/2020 WED 10AM',
      url: ["https://email-gallery.netlify.app/emails/2020-08-event__invite-retirement-nt-act.html"],
    },
    { 
      name: '[RIF] 2020-08 (QLD) - Invite',
      color: 'gold',
      group: 'event',
      sent: '421',
      opens: '259 - 61.52% ',
      clicks: '31 - 7.36% ',
      subject: 'You’re invited to attend an exclusive member webinar',
      time: '11/08/2020  TUE 5:15pm',
      url: ["https://email-gallery.netlify.app/emails/2020-08-event__invite-retirement-qld.html"],
    },
    { 
      name: '[RIF] 2020-07 (NSW) - Reminder',
      color: 'gold',
      group: 'event',
      sent: '1,163',
      opens: '563 - 48.41% ',
      clicks: '46 - 3.96% ',
      subject: 'Cbus Webinars: Don’t miss out – Reserve your spot. 🔔',
      time: '29/07/2020 WED 10:00AM',
      url: ["https://email-gallery.netlify.app/emails/2020-07-event__invite-retirement--nsw-reminder.html"],
    },
    { 
      name: '[RIF] 2020-07 (NSW) - Invite',
      color: 'gold',
      group: 'event',
      sent: '2,326',
      opens: '1,341 - 57.65%',
      clicks: '134 - 5.76% ',
      subject: 'You’re invited to attend an exclusive member webinar',
      time: '07/07/2020 TUE 10:00AM',
      url: ["https://email-gallery.netlify.app/emails/2020-07-event_rif-nsw-invite"],
    },

    ],
    paginate: 1000,
    paginate_total: 0,
    search_filter: '',
    status_filter: ''
  },
  created: function () {
    this.search_filter= getParameterByName('search');
  },
  methods: {
    selectItem(item) {
      this.active = item;
    },
    setPaginate: function (i) {
      if (this.current == 1) {
        return i < this.paginate;
      }
      else {
        return (i >= (this.paginate * (this.current - 1)) && i < (this.current * this.paginate));
      }
    },
    setStatus: function (status) {
      this.status_filter = status;
      this.$nextTick(function () {
        this.updatePaginate();
      });
    },
    updateCurrent: function (i) {
      this.current = i;
    },
    updatePaginate: function () {
      this.current = 1;
      this.paginate_total = Math.ceil(document.querySelectorAll('tbody tr').length/this.paginate);
    }
  }
});


setTimeout(function(){
  $("#myInput").focus();
}, 2000);


// Filter in URL
function getParameterByName(name, url) {
  if (!url) url = window.location.href;
  name = name.replace(/[\[\]]/g, '\\$&');
  var regex = new RegExp('[?&]' + name + '(=([^&#]*)|&|#|$)'),
      results = regex.exec(url);
  if (!results) return null;
  if (!results[2]) return '';
  return decodeURIComponent(results[2].replace(/\+/g, ' '));
}


$(".load").hide();
setTimeout(function(){
	$(".load").show();
},3000);

$(".loading").show();
setTimeout(function(){
	$(".loading").hide();
},3000);


// Hide nav on shared URL
if (window.location.href.indexOf("search=") != -1) {
  $("#nav").hide();
  }