vue-main.jsnew Vue({
  el: '#items',
  created() {
    this.paginate_total = this.items.length/this.paginate;
  },
  data: {
     current: 1,
     items: [
      { name: 'Holden Template new logo, 2019', group: 'template', url: ["https://isobaraustralia.createsend.com/templates/preview/a98a0f3aa84af532"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden_2019.jpg"],},
      { name: 'Isobar Art Exhibition Risk, 2019', group: 'event', url: 'https://isobaraustralia.createsend1.com/t/ViewEmail/y/6300E8602EE12187', pic: 'https://studio-media.netlify.com/img/email-showcase/showcase/iso-risk.jpg'},
      { name: 'Isobar NON Colour, 2019', group: 'event', url: 'https://isobaraustralia.createsend1.com/t/ViewEmail/y/DEF3C090ABDAD810', pic: 'https://studio-media.netlify.com/img/email-showcase/showcase/iso-non-19.jpg'},
      { name: 'Isobar Fit & healthy, 2019', group: 'event', url: 'https://isobaraustralia.createsend1.com/t/ViewEmail/y/5AB925D7BE63AEF6', pic: 'https://studio-media.netlify.com/img/email-showcase/showcase/iso-hf.jpg'},
      { name: 'Grid Template, 2019', group: 'template', url: 'http://createsend.com/t/y-C10DF2CFA6D9BD67', pic: 'https://studio-media.netlify.com/img/email-showcase/showcase/iso-grid.jpg'},
      { name: 'Klip Studio, 2019 April	', group: 'kinetic ', url: 'http://createsend.com/t/y-F919627F298B421F ', pic: 'https://studio-media.netlify.com/img/email-showcase/showcase/klipdesk.jpg'},
      { name: 'The perfect candidate | 2019 April	', group: 'kinetic', url: 'https://mailchi.mp/australianfutures/meet-the-perfect-candidate?e=e693eb72a0', pic: 'https://studio-media.netlify.com/img/email-showcase/showcase/tpc.jpg'},
      { name: 'Isobar Event Crafted, 2018 Nov	', group: 'event', url: 'https://isobaraustralia.createsend1.com/t/ViewEmail/y/A77C5FC52241B229', pic: 'https://studio-media.netlify.com/img/email-showcase/showcase/crafted.jpg'},
      { name: 'Isobar DesignOps and Design Systems! | 2018	', group: 'template', url: 'https://isobaraustralia.createsend1.com/t/ViewEmail/y/FED044184BC4CDA6', pic: 'https://studio-media.netlify.com/img/email-showcase/showcase/iso-do.jpg'},
      { name: 'Momatu App | 2018 Oct', group: 'template', url: 'https://isobaraustralia.createsend.com/t/ViewEmail/y/C59E8C1A1C504F34/C67FD2F38AC4859C', pic: 'https://studio-media.netlify.com/img/email-showcase/showcase/mom.jpg'},
      {name: 'AusPost: Shispter Template (2018 May)', group: 'marketing', url: ["https://isobarstudio.cmail19.com/t/ViewEmail/y/91DFFBD56A444B13/1701EFAE8EC2B1513FEC1D8A50AFD3BD"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/ap-shipster-2.jpg"],},
      {name: 'AusPost: Shispter: Image Carousel in Email', group: 'template', url: ["https://isobarstudio.cmail20.com/t/ViewEmail/y/DC29EEAF1D5B5600/1701EFAE8EC2B1513FEC1D8A50AFD3BD"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/shipster-slider.jpg"],},
      { name: 'Shipster, Grid template |  2018	', group: 'template', url: 'http://createsend.com/t/y-9CB12B556925E9CB', pic: 'https://studio-media.netlify.com/img/email-showcase/showcase/ap-shipster-2.jpg'},
      { name: 'Acadia, 2018 July', group: 'marketing', url: ["https://holden.createsend1.com/t/ViewEmail/y/3BC5419E6445DA45"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden-acadia.jpg"],},
      { name: 'TLDR, 2018 May', group: 'marketing ', url: ["http://isobaraustralia.cmail19.com/t/ViewEmail/y/C3312133ED1ADBDF/8461865F08801F77E89F0E32AAFB68BF"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/tldr.jpg"],},
      { name: 'Commodore (2018 Mar)', group: 'marketing', url: ["http://holden.createsend1.com/t/ViewEmail/y/EFDA3260693A33DE"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden--b.jpg"],},
      {name: 'NON 2017 ', group: 'kinetic', url: ["http://isobaraustralia.createsend1.com/t/ViewEmail/y/854AADE424985E5F"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/non.jpg"],},
      {name: 'Equinox (2017 Nov)', group: 'marketing ', url: ["http://holden.createsend1.com/t/ViewEmail/y/2FC7B297EC1C7CC7"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden--e.jpg"],},
      {name: 'Lion AU (2017 Dec)', group: 'marketing ', url: ["http://holden.createsend1.com/t/ViewEmail/y/2881A6D68613C52B"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/lion-2017.jpg"],},
      {name: 'Lion AU (2018 March)', group: 'marketing ', url: ["http://holden.createsend1.com/t/ViewEmail/y/D2A13CB45902C79A"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/lion-2018.jpg"],},
      {name: 'Captiva Gender targeting  (2017 Nov)', group: 'marketing targert kinetic ', url: ["http://holden.createsend1.com/t/ViewEmail/y/832BDB3F35D4C6DF"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden--c.jpg"],},
      {name: 'Liftback (2018 Mar)', group: 'marketing ', url: ["http://holden.createsend1.com/t/ViewEmail/y/00A6D649FDD10883"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden--lb.jpg"],},
      {name: 'TAC ePublication (2017 Oct)', group: 'marketing', url: ["https://visualjazz.createsend.com/t/ViewEmail/y/19331E05C4D1D312/C67FD2F38AC4859C"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/tac-2017.jpg"],},
      {name: 'AusPost: Shipster Launch (2017 Oct)', group: 'marketing', url: ["https://visualjazz.createsend.com/t/ViewEmail/y/9028A1C0AF338274/C67FD2F38AC4859C"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/shipster-1.png"],},
      {name: 'AusPost: Shipster Multi Msg (2017 Oct)', group: 'marketing', url: ["https://visualjazz.createsend.com/t/ViewEmail/y/7656D283AE2B754C/C67FD2F38AC4859C"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/shipster-2.png"],},
      {name: 'Shipster Click Frenzy (2018)', group: 'marketing ', url: ["https://isobaraustralia.createsend.com/t/ViewEmail/y/1D8065740EB81591/C67FD2F38AC4859C"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/click-1.jpg"],},
      {name: 'Shipster welcome (2017)', group: 'marketing ', url: ["https://isobaraustralia.createsend.com/t/ViewEmail/y/C5B7443E30F18590/C67FD2F38AC4859C"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/shop-1.jpg"],},
      {name: 'ShipsterTransactional  (2017)', group: 'marketing ', url: ["https://isobaraustralia.createsend.com/t/ViewEmail/y/8BDBAA4B1DE20B8D/C67FD2F38AC4859C/"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/shop-2.jpg"],},
      {name: 'Shipster Message C (2017)', group: 'marketing ', url: ["https://isobaraustralia.createsend.com/t/ViewEmail/y/3FC581F103A3F8C8/C67FD2F38AC4859C"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/shop-3.jpg"],},
      {name: 'Shipster Message A (2017)', group: 'marketing ', url: ["https://isobaraustralia.createsend.com/t/ViewEmail/y/327FFB7B36E0B81A/C67FD2F38AC4859C"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/shop-4.jpg"],},
      {name: 'Click Frenzy Mayhem (2017)', group: 'marketing', url: ["https://isobaraustralia.createsend.com/t/ViewEmail/y/3D620DADE30CD5A2/C67FD2F38AC4859C"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/click-2.jpg"],},
      {name: 'Click Frenzy - Orias (2017)', group: 'marketing', url: ["https://isobaraustralia.createsend.com/t/ViewEmail/y/0B944800CC08F933/C67FD2F38AC4859C"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/click-3.jpg"],},
      {name: 'Shop mate welcome (2017)', group: 'marketing', url: ["https://visualjazz.createsend.com/t/ViewEmail/y/7FE2B7BFB430653A/C67FD2F38AC4859C"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/shopMate-2017.jpg"],},
      {name: 'Holden 2018 base template dark', group: 'template', url: ["https://visualjazz.createsend.com/t/ViewEmail/y/FB98976B33E7A3D7/C67FD2F38AC4859C"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/base_dark.jpg"],},
      {name: 'Holden coming soon: (Equinox 2016 Sep)', group: 'marketing', url: ["http://holden.createsend1.com/t/ViewEmail/y/22A7F859D3A4FE8E"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/equinox.jpg"],},
      {name: 'Holden coming soon: Spark (2016)', group: 'marketing', url: ["http://holden.createsend1.com/t/ViewEmail/y/4DE4270100E484B3"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/spark.jpg"],},
      {name: 'isobarGood email (2018m April)', group: 'event', url: ["http://isobaraustralia.createsend1.com/t/ViewEmail/y/A0B1274CEA52B74F"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/isogood.jpg"],},
      {name: 'Innovation Council 2018 Template', group: 'marketing', url: ["http://dentsuaegis.createsend1.com/t/ViewEmail/y/EE1C3A807F1EB929"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/dan.jpg"],},
      {name: 'Shop mate payment (2017)', group: 'report', url: ["https://visualjazz.createsend.com/t/ViewEmail/y/560A47D43B55C9E3/C67FD2F38AC4859C"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/shopMate.jpg"],},
      {name: 'Lion (2018 Feb)', group: 'kinetic ', url: ["http://holden.createsend1.com/t/ViewEmail/y/9A5C9855FF8C3E29"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden--l.jpg"],},
      {name: 'Commodore Myths (2017 Dec)', group: 'kinetic', url: ["http://holden.createsend1.com/t/ViewEmail/y/71BC03315DE4D26D"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden--m.jpg"],},
      {name: 'Marvel: GIF ', group: 'kinetic', url: ["https://cdn2.hubspot.net/hubfs/2700725/Underarmor(1).gif?t=1495656554020"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/marvel.gif"],},
      {name: 'Holden 2018 base template light', group: 'template', url: ["https://visualjazz.createsend.com/t/ViewEmail/y/F955F0C0713A0BF9/C67FD2F38AC4859C"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/base_light.jpg"],},
      {name: 'Holden: 100HR Emjois (2017 Sep)', group: 'kinetic', url: ["http://holdenclient.cmail20.com/t/ViewEmail/y/BCF3B5A5D0A09813/DA77E062F9893914B4B1B1F623478121"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden-emoji.gif"],},
      {name: 'Click Frenzy, Go Wild (2017 Sep)', group: 'marketing', url: ["https://visualjazz.createsend.com/t/ViewEmail/y/31408A6FEC6C54E7/C67FD2F38AC4859C"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/clickFrenzy.jpg"],},
      {name: 'AusPost: Small Bizz  (2017 Oct)', group: ' marketing', url: ["https://visualjazz.createsend.com/t/ViewEmail/y/EC271B7BB5B53DBA/C67FD2F38AC4859C/?tx=0&previewAll=1&print=1"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/ap-sbn.jpg"],},
      {name: 'AusPost: Digi  (2017 May)', group: ' marketing', url: ["https://visualjazz.createsend.com/t/ViewEmail/y/2EE2E851FAAC7BC2/C67FD2F38AC4859C/?tx=0&previewAll=1&print=1"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/ap-digi.jpg"],},
      {name: 'Australian Government Department of Health (2017 Sep)', group: ' marketing', url: ["https://visualjazz.createsend.com/t/ViewEmail/y/FECE5AE3FEC993E0/C67FD2F38AC4859C/?tx=0&previewAll=1&print=1"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/dept-health.jpg"],},
      {name: 'Holden: Colorado (2017 Aug)', group: 'marketing ', url: ["http://holden.createsend1.com/t/ViewEmail/y/E9C3555F105C7B7D"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden-3.jpg"],},
      {name: 'Holden: Astra (2017 Jul)', group: 'kinetic', url: ["http://holden.createsend1.com/t/ViewEmail/y/C24F913C8B56774C"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden-4.jpg"],},
      {name: 'Holden: Maps (2017 Jul)', group: 'marketing', url: ["http://holden.createsend1.com/t/ViewEmail/y/699A995078DC89F3"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden-5.jpg"],},
      {name: 'Holden Lion: Wide template.  player GIF. VML Background', group: 'kinetic', url: ["http://holden.createsend1.com/t/ViewEmail/y/D2B658E362B40FA4"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden-lion-1.jpg"],},
      {name: 'Wide Email Template - Image Carousel & VML background', group: 'kinetic  interactive ', url: ["https://codepen.io/DonnaG/full/wdOoOJ/"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/templates/carousel-sample.jpg"],},
      {name: 'Holden CM Master template (Sep 1017)', group: 'brand: marketing cmTemplate ', url: ["https://visualjazz.createsend.com/templates/preview/8592d634925a4f53"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden-cm-template.jpg"],},
      {name: 'Racing Victoria | transactional template (2017 Sep)', group: 'brand: other report', url: ["https://visualjazz.createsend.com/t/ViewEmail/y/91EDA739FC49F3DB/C67FD2F38AC4859C"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/r-vic.gif"],},
      {name: 'B&Q 2018', group: '  marketing announcement kinetic interactive', url: ["https://info.diy.com/pub/sf/FormLink?_ri_=X0Gzc2X%3DYQpglLjHJlTQGNitYovzdzdnw9zbU8NHEjLM2LzbzejBHKDvoem97v4WzcnEzgoq50FEF8kOnI0iRVXMtX%3DYQpglLjHJlTQGmCzgw7bnCpgza37RDSpWLKmwC0C3q9ohOqzdUWAWqkXo3MH1yv3uUNrNKkof&_ei_=EnuCPcG29E8GGr2z_8aX4DgmNMTjEv5I083F4CiayFEdX5Kt7HtjmHWxW5R-pVm9Z7dmBulUxRT3TQpaK2AtU603s6W-vzpthZBG2NcqXSVrqYlHynq1yY47kOUmZ1LeLEmts1mfNAl7T1E_YxBU7Oxf9fFmVfBO44mH2EFkCAmGsJh5fhNGY7LX4kDY_HWpykvvgwwoQ8nYvr2R0-e3tc6agb2r0ugcR78YaAoebqkOIfjEvsKI9lCEZz9GmrjABWVoq46RCD1wE2FLnlp1xQNHFdL4zSBRwM0Jpw2f4jNb9MHfyud8CHJgP5Ol_PfNUlSs6C7P3nlek-4w9R7XUWDGdRSzZcmLDeRnkLn113vs6GCnmClE1V7BiBDAZCqkNZw6jVmuHYoBsm1O8Gg9u6Ow-Bx8xGIm1Jc94EVSTCyUKFrb7_ehN8lUz4TSGANQ646q5xo4pUghS0."], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/b&q.jpg"],},
      {name: 'Fargo 2017', group: ' marketing announcement kinetic ', url: ["http://kristianrobinson.co.uk/FARGO/fargo.html"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/fargo.jpg"],},
      {name: 'invisionapp (SEP, 2017)', group: ' ', url: ["http://get.invisionapp.com/available-now-embed-live-invision-projects-into-trello-and-confluence?ecid=ACsprvt2H_DnpGcSiI8BPgOf9a94KpTW05MBil4JyqoXepYZlcZRYmbTURIv93ofXfKwu0rNp6TO&utm_campaign=Product%20Updates"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/invision-2017.jpg"],},
      {name: 'Emailmonks: Form in email', group: 'kinetic interactive', url: ["http://www.emailmonks.com/form-in-email.html?email=donna.galletta@isobar.com"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/emailmonks_2.jpg"],},
      {name: 'Holden: Hamburger Menu', group: 'kinetic marketing interactive', url: ["http://isobaraustralia.cmail19.com/t/ViewEmail/y/7E1A71C4074D6743"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden-1.jpg"],},
      {name: 'Carousel Hotspots', group: 'kinetic interactive', url: ["http://holden.cmail20.com/t/ViewEmail/y/5F94048887D5F74D"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/exp-1.jpg"],},
      {name: 'Shop mate reminder , colour block (2017)', group: 'marketing report', url: ["https://visualjazz.createsend.com/t/ViewEmail/y/B1EDD9DD9919BD71/C67FD2F38AC4859C/?tx=0"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/shopmate1.jpg"],},
      {name: 'invisionapp (MAR 2018)', group: ' ', url: ["https://goo.gl/jNK34o"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/invision.jpg"],},
      {name: 'isobar social update  (2018, April)', group: 'isobar event cmTemplate', url: ["http://isobaraustralia.createsend1.com/t/ViewEmail/y/FA027B6B7B583967"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/toh.jpg"],},
      {name: 'Holden: Personalised Image & bottom shadow', group: 'kinetic holden target', url: ["http://isobarstudio.createsend1.com/t/ViewEmail/y/F7C67EED9600F6A8"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden-p-image.jpg"],},
      {name: 'JetStar (2017)', group: 'kinetic ', url: ["https://goo.gl/wlzljr"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/jet2017.jpg"],},
      {name: 'Commodore, promo block (2018 Mar)', group: 'marketing', url: ["http://holden.createsend1.com/t/ViewEmail/y/97B46D6E496BBD4F"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden_o.jpg"],},
      {name: 'Holden: Service Maps', group: 'marketing', url: ["http://holden.createsend1.com/t/ViewEmail/y/2CAD671E786A51FE"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden-maps.jpg"],},
      {name: 's Sample', group: 'kinetic ', url: ["http://codepen.io/DonnaG/full/KaNGbb/"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/exp-2.gif"],},
      {name: 'JetStar (2016)', group: 'kinetic  ', url: ["https://goo.gl/UY3Zvb"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/jet2016.jpg"],},
      {name: 'Social Media Feed', group: 'kinetic ', url: ["http://isobaraustralia.createsend1.com/t/ViewEmail/y/1C78E4B21FBE912D/"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/exp-3.jpg"],},
      {name: 'Rollover Hover image', group: 'kinetic interactive', url: ["http://codepen.io/DonnaG/full/bBzeJx/"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/exp-4.gif"],},
      {name: 'Australia Post', group: 'marketing template htmlTemplate', url: ["https://visualjazz.createsend.com/t/ViewEmail/y/61AD988DCEE74BA1/C67FD2F38AC4859C/"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/ap-1.gif"],},
      {name: 'Australia Post: Image Carousel in Email', group: 'kinetic marketing template interactive', url: ["https://visualjazz.createsend.com/t/ViewEmail/y/5CD5EC478C97A19C/C67FD2F38AC4859C/?tx=0&previewAll=1&print=1"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/ap-2.gif"],},
      {name: 'Sportsbet: Countdown', group: 'kinetic', url: ["http://isobaraustralia.createsend1.com/t/ViewEmail/y/71CE28F3F8F659A7"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/sb-1.gif"],},
      {name: 'isobar (2018, April)', group: 'kinetic ', url: ["https://visualjazz.createsend.com/templates/preview/63efd8ac5776c14f"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/iso2018.jpg"],},
      {name: 'JetStar (2017, May)', group: 'kinetic ', url: ["https://goo.gl/Vin4Aw"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/jet.jpg"],},
      {name: 'Innovation Council', group: 'template', url: ["http://dentsuaegis.createsend1.com/t/ViewEmail/y/814D57F527F89A56"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/da-1.jpg"],},
      {name: 'Experience Design ', group: 'template', url: ["http://isobaraustralia.createsend1.com/t/ViewEmail/y/49EBA14B144CE794"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/iso-1.jpg"],},
      {name: 'Uniqlo: Pac Fair', group: 'marketing', url: ["http://uniqlo.createsend1.com/t/ViewEmail/y/61C0A778A94037F3"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/uni-1.jpg"],},
      {name: 'Holden: Xmas Card, End Of year', group: 'holden seasonal', url: ["https://visualjazz.createsend.com/t/ViewEmail/y/34344D91DE0D9AEC/C67FD2F38AC4859C"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden-2.jpg"],},
      {name: 'Holden: Xmas Card, NZ', group: 'event', url: ["http://holden.createsend1.com/t/ViewEmail/y/B94187EAA6AF054F"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden-nz-xmas.jpg"],},
      {name: 'Isobar: Xmas Party', group: 'isobar seasonal event', url: ["http://isobaraustralia.createsend1.com/t/ViewEmail/y/2C223C22D890D28F"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/isobar-xmas-party.jpg"],},
      {name: 'Personalised Image', group: 'kinetic target', url: ["http://isobarstudio.createsend1.com/t/ViewEmail/y/2CD447904263BCA2"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/templates/basic-personalised.jpg"],},
      {name: 'Spotify: Your 2016 in music', group: ' marketing', url: ["https://litmus.com/scope/nwimrouj6up2"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/spotify.gif"],},
      {name: 'Student Flights: Emoji  Email', group: 'kinetic', url: ["img/email-showcase/showcase/studentflights.jpg"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/studentflights.jpg"],},
      {name: 'Jetstar: Hoilday Sale. Wide background image', group: ' marketing', url: ["https://goo.gl/Vin4Aw"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/jetstar.jpg"],},
      {name: 'Email Monks: Rich media in email', group: ' marketing ', url: ["https://goo.gl/7BJt1d"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/emailmonks.jpg"],},
      {name: 'Email Monks Easter  Email', group: 'kinetic', url: ["https://goo.gl/XpPWwC"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/monks.jpg"],},
      {name: 'Sonic Game', group: 'kinetic', url: ["http://kristianrobinson.co.uk/sonic/sonic_webkit_experiment.html"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/sonic.jpg"],},
      {name: 'Mario Game', group: 'kinetic', url: ["http://isobarstudio.createsend1.com/t/ViewEmail/y/9A9A72FCC48DD603"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/mario.jpg"],},
      {name: 'Email On Acid Halloween', group: 'kinetic', url: ["https://goo.gl/Y7CrFQ"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/game_01.jpg"],},
      {name: 'Taco Bell 8-bit', group: 'kinetic', url: ["http://tacobell.mkt7706.com/breakfastjourneyB?spMailingID=25049323&spUserID=MjQwNjA2OTAxNjcwS0&spJobID=763793532&spReportId=NzYzNzkzNTMyS0"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/taco-bell-2.jpg"],},
      {name: 'Taco Bell', group: 'kinetic', url: ["https://litmus.com/builder/f8a8c1f"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/taco-bell.jpg"],},
      {name: 'Two UK Xmas', group: 'kinetic', url: ["http://twouk.cmail20.com/t/ViewEmail/d/7BBAF227BB35BE3A/FA12A463E9E5A76B4E9AB52EF5D51DA2"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/2uk.jpg"],},
      {name: 'Missguided: Triggered Email', group: ' marketing', url: ["https://au.pinterest.com/pin/318489004882530205/"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/missguided.gif"],},
      {name: 'Mailchimp: 2016 Report', group: ' marketing report', url: ["https://au.pinterest.com/pin/351210470926681930/"], pic: ["https://s-media-cache-ak0.pinimg.com/564x/97/01/2b/97012beb3a9e9a6dab05fb311017e57b.jpg"],},
      {name: 'Basic Template', group: 'template', url: ["http://isobarstudio.createsend1.com/t/ViewEmail/y/22B5EDB9F0A3498B"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/templates/basic.gif"],},
      {name: 'Feature Background Template', group: 'kinetic', url: ["http://isobarstudio.createsend1.com/t/ViewEmail/y/229CFB49F9E596D6"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/templates/feature-background.gif"],},
      {name: 'Feature Columns Template', group: 'template', url: ["http://isobarstudio.createsend1.com/t/ViewEmail/y/221FCA14CA0D10A8"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/templates/Feature_columns.gif"],},
      {name: 'Hamburger Menu - Feature Template', group: 'kinetic', url: ["http://isobarstudio.createsend1.com/t/ViewEmail/y/68CD62FBB29AD7A1"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/templates/hm-feature.gif"],},
      {name: 'Hamburger Menu - Feature Columns Template', group: 'template', url: ["http://isobarstudio.createsend1.com/t/ViewEmail/y/4B1B18222DE050F6"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/templates/hm-feature-coloumns.gif"],},
      {name: 'Promo Strips Template', group: 'template', url: ["http://isobarstudio.createsend1.com/t/ViewEmail/y/DCB2005B780A1080"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/templates/promo-strips.gif"],},
      {name: 'Review Quote Template', group: 'template report', url: ["http://isobarstudio.createsend1.com/t/ViewEmail/y/98284BDF4EF9EEA6"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/templates/review-quote.gif"],},
      {name: 'Review Report Template', group: 'template report target', url: ["http://isobarstudio.createsend1.com/t/ViewEmail/y/228F9ADA42C8FE06"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/templates/review-report.gif"],},
      {name: 'Feature Blog: Background Image and PNG Image Template', group: 'kinetic ', url: ["http://isobarstudio.createsend1.com/t/ViewEmail/y/899513A4BFEAAD25"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/templates/feature-blog.jpg"],},
      {name: 'Background image with text overlay', group: 'kinetic ', url: ["http://isobarstudio.createsend1.com/t/ViewEmail/y/77363EC3138A8489"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/templates/feature-bg-overlay.jpg"],},
      {name: 'Xmas Card: Animated GIF Background Template', group: 'kinetic gif  seasonal', url: ["http://isobarstudio.createsend1.com/t/ViewEmail/y/4698CC025C2BB587"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/templates/card-snow.gif"],},
      {name: 'Outfitters: April fools', group: 'seasonal  marketing', url: ["https://au.pinterest.com/pin/558376053780229136/"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/outfitters.jpg"],},
      {name: 'Bonobos: April fools', group: 'seasonal  marketing', url: ["https://au.pinterest.com/pin/860750547501322533/"], pic: ["https://s-media-cache-ak0.pinimg.com/564x/d4/61/e6/d461e6e15c4d51a48fcd0dcea155b029.jpg"],},
      {name: 'Apology Pet store', group: 'apology  marketing target', url: ["https://s-media-cache-ak0.pinimg.com/564x/29/22/1f/29221feea1ba2d77e0502aa9d11348e2.jpg"], pic: ["https://s-media-cache-ak0.pinimg.com/564x/29/22/1f/29221feea1ba2d77e0502aa9d11348e2.jpg"],},
      {name: 'Grammarly - Weekly report', group: ' marketing report', url: ["https://visualjazz.createsend.com/t/ViewEmail/y/805A8225F41241F3/C67FD2F38AC4859C/?tx=0"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/gram.jpg"],},
      {name: 'The Good Guys Xmas Card', group: ' seasonal', url: ["http://isobarstudio.createsend1.com/t/ViewEmail/y/833AD88EEB9D32F6"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/tgg.jpg"],},
      {name: 'Holden: Trax Series Comp - Market Rummaging', group: 'marketing target', url: ["http://holden.createsend1.com/t/ViewEmail/y/CAF41537C16D0653"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden-trax-market.jpg"],},
      {name: 'Holden: Trax Series Comp - Karoke', group: 'marketing target', url: ["http://holden.createsend1.com/t/ViewEmail/y/540102199A23D962"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden-trax-karoke.jpg"],},
      {name: 'Holden: Trax Series Comp - Food Fun', group: 'marketing target', url: ["http://holden.createsend1.com/t/ViewEmail/y/891E1BA4F011BED3"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden-trax-food.jpg"],},
      {name: 'Holden: Trax Series Comp - Coffee Run', group: 'marketing target', url: ["http://holden.createsend1.com/t/ViewEmail/y/4E8FF50B33CA45E9"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden-trax-coffee.jpg"],},
      {name: 'Holden: Barina Test Drive', group: 'marketing target', url: ["http://holden.createsend1.com/t/ViewEmail/y/E775F5FB54BAB110"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden-barina.jpg"],},
      {name: 'Holden: Commodore MotorSport', group: 'marketing target', url: ["http://holden.createsend1.com/t/ViewEmail/y/096A6D318489770C"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden-com-msport.jpg"],},
      {name: 'Holden: Lion ', group: 'marketing ', url: ["http://holden.createsend1.com/t/ViewEmail/y/6906049B6CBD05BB"], pic: ["https://studio-media.netlify.com/img/email-showcase/showcase/holden-lion.jpg"],}

    ],
    paginate: 1000,
    paginate_total: 0,
    search_filter: '',
    status_filter: ''
  },
  methods: {
    setPaginate: function (i) {
      if (this.current == 1) {
        return i < this.paginate;
      }
      else {
        return (i >= (this.paginate * (this.current - 1)) && i < (this.current * this.paginate));
      }
    },
    setStatus: function (status) {
      this.status_filter = status;
      this.$nextTick(function () {
        this.updatePaginate();
      });
    },
    updateCurrent: function (i) {
      this.current = i;
    },
    updatePaginate: function () {
      this.current = 1;
      this.paginate_total = Math.ceil(document.querySelectorAll('tbody tr').length/this.paginate);
    }
  }
});
