const searchWords = {
  webinar: "webinar, event, seminar, education sessions",
  laptop: "laptop, register online, webinar, event, education sessions",
  "laptop-lines": "laptop, register online, enter details",
  "phone-hand": "Call, Phone, App, Login keep on track",
  "no-tax": "no tax benefit",
  "money-down": "track money, investment updates, performance decrease",
  "chart-up": "track money, investment updates, performance",
  "chart-up-solid": "track money, investment updates, performance",
  "hand-clock": "access to super when needed, time saver benefit",
  "click-button": "login online, Log in to Employer Portal",
  "click-button-action": "Submit online, Submit your payment",
  "cash-in-hand": "Get a regular pay check in retirement, money benefit",
  "calendar-tick-chart":
    "Your super will continue to work for you in retirement, managed benefit",
  "date-target": "Target, managed benefit",
  "media-snapboard": "movie clapperboard, performance, media work job",
  "hardhat-light": "Hardhat light, construction work job",
  factory: "factory, building",
  "work-cart": "work cart, moving resources",
  "wallet-cash": "cash, wallet, cash sticking out of wallet",
  "paperwork-done": "document, tick, approve document",
  "list-tick": "checklist, checkmark, tick, list",
  piggybank: "pig, piggybank, coins, savings",
  toiletpaper: "toilet paper, wasting money",
  "money-globe": "lightbulb, dollar sign, idea",
  "money-paperwork-done": "document, statement, tick, money",
  umbrella: "umbrella",
  "coffee-cup": "coffee",
  renewable: "leaf, bolt, cycle",
  "first-place": "first place, podium, winner, star",
  sunset: "sunset, landscape, mountains",
  "group-people-list": "customer, advisor, desk, consultation",
  "support-person": "support, help",
  "front-counter": "customer, advisor, desk, consultation",
  "hand-swipe": "hand, gesture, left, right, horizontal",
  "hand-shake": "handshake, gesture",
  "web-search": "mouse, form, field, input",
  calculator: "calculator, hand, push button",
  "list-done": "document, checklist, tick, approve",
  "money-plant": "money, plant, growth",
  "super-health-check-stethoscope":
    "stethoscope, money, health, financial health",
  transfer: "tick, coin, cycle",
};

module.exports = searchWords;
